ludeeus/awesomeversion

awesomeversion/awesomeversion.py, awesomeversion/match.py, tests/test_compare.py
Fixes an issue where this would return `False` while it should return `True`
```python
from awesomeversion import AwesomeVersion
current = AwesomeVersion("2021.1.0b0")
upstream = AwesomeVersion("2021.1.0b1")
print(upstream > current)
```
=> Fix issue with comparing modifiers

.codecov.yml, .github/workflows/actions.yml, README.md
Add codecov to Actions, and status badges
=> Add codecov

.coveragerc, awesomeversion/awesomeversion.py, awesomeversion/comparehandlers/__init__.py, awesomeversion/comparehandlers/base.py, awesomeversion/comparehandlers/container.py, awesomeversion/comparehandlers/dev.py, awesomeversion/comparehandlers/modifier.py, awesomeversion/comparehandlers/sections.py, awesomeversion/comparehandlers/simple.py, awesomeversion/handlers.py, awesomeversion/strategy.py, setup.py, tests/test_compare.py, tests/test_handlers.py
split compare handlers to `awesomeversion.comparehandlers` for a more modular codebase.
=> Split compare handlers

awesomeversion/__init__.py, awesomeversion/exceptions.py
```python
from awesomeversion import AwesomeVersion, AwesomeVersionException
try:
AwesomeVersion("20") > AwesomeVersion("unknown")
except AwesomeVersionException:
print("Oh boy!")
```
=> Add AwesomeVersionException and expose it in package root

awesomeversion/handlers.py, awesomeversion/match.py, awesomeversion/strategy.py, tests/test_match.py
=> Cleanup old special handler logic

awesomeversion/awesomeversion.py, awesomeversion/match.py, tests/issues/test_issue14.py
- This PR fixes or closes issue: fixes #14
=> Fix issue with alpha/beta/dev if no modifier

.pylintrc, README.md, awesomeversion/awesomeversion.py, tests/test_compare.py
```python
from awesomeversion import AwesomeVersion
with AwesomeVersion("20.12.0") as current:
assert "2020.12.1" > current
with AwesomeVersion(1) as current:
assert 2 > current
```
=> Allow compare with string and int

.github/workflows/verify.yml, .github/workflows/verify_issue.yml, requirements.txt, scripts/create_test_from_issue.py, tests/issues/test_issue14.py
=> Test code examples provided in issues

.github/workflows/actions.yml, .github/workflows/release-drafter.yml, awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
This will allow for this kind of operations without the need for a custom decoder
```python
import json
from awesomeversion import AwesomeVersion
version = AwesomeVersion("20.12.1")
print(json.dumps({"name": "test", "version": version}))
> {"name": "test", "version": "20.12.1"}
```
=> Make AwesomeVersion JSON serializable

scripts/create_test_from_issue.py
=> Ignore issues without a python block

awesomeversion/awesomeversion.py, awesomeversion/match.py, tests/test_awesomeversion.py
Adds `AwesomeVersion.prefix` to return the version prefix if any.
=> Add prefix property

awesomeversion/awesomeversion.py, tests/issues/test_issue26.py
Strip version strings on initialization of the object.
- This PR fixes or closes issue: fixes #26
=> Strip version strings

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
Improve the handling with new representation from #28
=> Improve representation handling

README.md, awesomeversion/comparehandlers/dev.py, awesomeversion/comparehandlers/sections.py, awesomeversion/comparehandlers/simple.py, awesomeversion/handlers.py, tests/test_awesomeversion.py, tests/test_compare.py, tests/test_equals.py
=> Fix issue with comparing with .devXXX modifier

awesomeversion/handlers.py, tests/test_compare.py
=> Copy objects to prevent modification

Makefile, awesomeversion/awesomeversion.py, awesomeversion/comparehandlers/base.py, awesomeversion/comparehandlers/container.py, awesomeversion/comparehandlers/dev.py, awesomeversion/comparehandlers/modifier.py, awesomeversion/comparehandlers/sections.py, awesomeversion/comparehandlers/simple.py, awesomeversion/handlers.py, awesomeversion/match.py, tests/test_awesomeversion.py, tests/test_compare.py
Adds support for versions like these `1.0.0-beta2` & `1.0.0-beta.2`
=> Add support for versions like `1.0.0-beta2` & `1.0.0-beta.2`

awesomeversion/awesomeversion.py, tests/test_compare.py
=> Fix issue with comparing against float

awesomeversion/comparehandlers/simple.py, tests/test_compare.py, tests/test_handlers.py
Fixes issue with `>` and `<` compare against simplever.
=> Fix simplever compare handler

awesomeversion/awesomeversion.py
=> Fix property types

awesomeversion/__init__.py, awesomeversion/awesomeversion.py, awesomeversion/exceptions.py, tests/test_awesomeversion.py
=> Add staticmethod ensure_strategy

awesomeversion/comparehandlers/modifier.py, awesomeversion/comparehandlers/sections.py, tests/test_compare.py
Cast modifier group to int so compare with 10 does not fail.
=> Fix issue with compare SemVer modifier with 10

awesomeversion/awesomeversion.py, requirements.txt, tests/test_awesomeversion.py
Deprecate the staticmethod `ensure_strategy` in favour of allowing the strategy/strategies to be passed as a second argument to `AwesomeVersion`
From:
```pyhton
AwesomeVersion.ensure_strategy("1.0.0", AwesomeVersionStrategy.SEMVER)
```
To:
```pyhton
AwesomeVersion("1.0.0", AwesomeVersionStrategy.SEMVER)
```
=> Deprecate staticmethod ensure_strategy

.github/workflows/actions.yml, README.md, setup.py
=> Remove Python 3.10

awesomeversion/comparehandlers/devrc.py, awesomeversion/handlers.py, tests/test_compare.py
=> Fix rc comparision with final release (X.X.rcX < X.X)

.github/workflows/actions.yml, README.md, requirements.txt, scripts/create_test_from_issue, setup.py
=> Enable 3.10.0-beta

.github/workflows/actions.yml
=> Fix codecov uploads

.github/workflows/actions.yml, .pylintrc, Makefile, README.md, awesomeversion/handlers.py, awesomeversion/match.py, pyproject.toml, requirements.txt
Add pylint to action CI and to  `make lint`
=> Add pylint checks

setup.py
With https://github.com/ludeeus/awesomeversion/pull/76 typing information can be shipped with the package to be used in other projects which wish to enable type checks.
For this `py.typed` should be included according to [PEP 561](https://www.python.org/dev/peps/pep-0561/).
=> Distribute type information

awesomeversion/awesomeversion.py
=> Adjustments for pylint R1714

awesomeversion/awesomeversion.py
=> Improve performance by avoiding gt/lt check when versions are equal

awesomeversion/awesomeversion.py, tests/issues/test_issue96.py
=> Use Enum values in f strings

.github/workflows/actions.yml, README.md
=> Add testing for Python 3.11-dev

README.md, awesomeversion/awesomeversion.py, requirements.txt
=> Add more examples to README

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py, tests/test_strategy.py
=> Add `valid` property to indicate that the version is not unknown

awesomeversion/awesomeversion.py, tests/test_compare.py
=> Show the version tried when raising AwesomeVersionCompareException

.github/ISSUE_TEMPLATE/bug.yml, .github/workflows/actions.yml, README.md
Currently does not work with testing requirements, and since it's dev there is no real need to test it.
=> Remove python 3.11-dev testing

awesomeversion/comparehandlers/modifier.py, poetry.lock, pyproject.toml
=> Bump black from 21.12b0 to 22.1.0

awesomeversion/awesomeversion.py, awesomeversion/comparehandlers/container.py, awesomeversion/comparehandlers/devrc.py, awesomeversion/comparehandlers/modifier.py, awesomeversion/comparehandlers/sections.py, awesomeversion/comparehandlers/simple.py, awesomeversion/strategy.py, awesomeversion/typing.py, tests/test_handlers.py, tests/test_version_scheme.py
Since Python 3.6 is no longer supported we can now use `from __future__ import annotations`, this has been added in this PR.
=> Import and use annotations

awesomeversion/awesomeversion.py
=> Return early for string match

awesomeversion/awesomeversion.py, awesomeversion/comparehandlers/modifier.py, tests/issues/test_issue153.py, tests/test_handlers.py
=> Do section compare before modifier

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
=> Allow more strategies for major,minor,patch

awesomeversion/awesomeversion.py, awesomeversion/comparehandlers/sections.py, awesomeversion/utils/regex.py, tests/test_compare.py
This allows comparing non-defined modifiers like `1.2.3-2 > 1.2.3-1`
=> Add better semver support

awesomeversion/awesomeversion.py, awesomeversion/utils/logger.py, tests/test_awesomeversion.py
=> Remove deprecated method `AwesomeVersion.ensure_strategy`

.devcontainer.json
=> Change devcontainer

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
find_first_match is not used without ensure_strategy, now it will raise when ensure_strategy is missing to guard against misconfiguration.
=> Do not allow find_first_match without ensure_strategy

awesomeversion/awesomeversion.py
=> Correct spelling mistakes

awesomeversion/comparehandlers/modifier.py
- This PR fixes or closes issue: fixes #176
=> Handle KeyError

awesomeversion/awesomeversion.py
The typing of _compare_versions was wrong only AwesomeVersion objects are passed here.
Since we already have AwesomeVersion objects there is not nee to create new ones for each compare handler which should make it more preformant.
=> _compare_versions takes AwesomeVersion not str

.devcontainer.json, .github/ISSUE_TEMPLATE/bug.yml, .github/workflows/actions.yml, README.md, poetry.lock, pyproject.toml
This adds Python 3.11 to the CI.
=> Add CI for Python 3.11

.github/workflows/demo.yml, demo/index.html
Adds a PyScript based demo page.
=> Add demo page

demo/index.html
Make the demo look prettier with some styles
=> Add better styles to demo

poetry.lock, pyproject.toml
=> Remove setuptools from dev-dependencies

demo/index.html
=> Update demo with compare

.github/workflows/actions.yml
=> Add Python 3.12 to CI

.github/PULL_REQUEST_TEMPLATE.md, README.md
=> Restructure README contents

.github/ISSUE_TEMPLATE/bug.yml, .github/workflows/actions.yml, README.md, pyproject.toml
As of 27 Jun 2023 Python 3.7 is EOL, support for < 3.8 has been removed.
=> Remove support for Python 3.7

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
=> Add __hash__ dunder

.github/workflows/actions.yml
=> Set checkout depth to 0 in codecov action

awesomeversion/awesomeversion.py
Currently, this throws `AwesomeVersionCompareException` when these are checked against versions that not have them.
Forcing string here makes the diff output more robust.
=> Force string when checking diff

awesomeversion/awesomeversion.py, tests/snapshots/unknown/.json, tests/test_versions.py
While passing in a blank string `""` as the version will not result in anything useful, before this PR the `sections` property would fail with a `IndexError` exception.
=> Fix sections property with blank string

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
The `_AwesomeVersionBase` base class was added to workaround a serialization issue with the default `json.dumps` function, this is no longer needed and the workaround has been removed.
=> Remove base class workaround

awesomeversion/awesomeversion.py, tests/issues/test_issue96.py, tests/test_awesomeversion.py
Remove the option to use positional arguments.
=> Remove deprecated positional arguments

awesomeversion/awesomeversion.py, tests/test_awesomeversion.py
In 2025 AwesomeVersion will start to raise an exception if find_first_match is passed without ensure_strategy
=> Add timeframe to warning about using find_first_match without ensure_strategy

.github/workflows/release.yml
=> Split release flow into two jobs (build/publish)

.github/workflows/actions.yml
=> Use correct depth argument for checkout action

demo/index.html
=> Update demo to trigger on input

benchmarks/__init__.py, benchmarks/const.py, benchmarks/test_compare.py, benchmarks/test_constructor.py, pyproject.toml
=> Use better names for parametrized benchmarks

.github/workflows/actions.yml, .github/workflows/codeql-analysis.yml, .github/workflows/codspeed.yml, .github/workflows/demo.yml
=> Add workflow permissions

.github/release.yml
=> Exclude PRs marked with test from release notes

.github/release.yml
=> Exclude PRs marked with repository from release notes

awesomeversion/awesomeversion.py
Previously this would loop over all matching and use the latest, but we should break on first hit.
=> Break after first hit with find_first_match

awesomeversion/awesomeversion.py
Use functools.cached_property to speedup accessing the major property.
=> Use cached_property for the major property

awesomeversion/awesomeversion.py
Use functools.cached_property to speedup accessing the minor property.
=> Use cached_property for the minor property

awesomeversion/awesomeversion.py
Use functools.cached_property to speedup accessing the simple property.
=> Use cached_property for the simple property

.github/workflows/codspeed.yml
=> Set full tag names in actions

awesomeversion/awesomeversion.py, awesomeversion/utils/regex.py, tests/test_coverage_edge_cases.py
More optimisations for common paths.
=> Refactor AwesomeVersion comparison methods and optimize regex patterns for performance

awesomeversion/awesomeversion.py, awesomeversion/strategy.py
=> Refactor AwesomeVersion comparison methods for improved validation and strategy handling

demo/index.html
=> Enhance interactive demo with improved styling, version comparison features, and single version analysis

demo/index.html
Fixes 2 warnings that were present in the console while viewing the demo.
=> Fix some demo warnings
